services:
  db:
    env_file: .env
    image: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 10
  app:
    env_file: .env
    build: .
    environment:
      - DATABASE_URL=db
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
      - 3002:3002
      - 3003:3003/tcp
      - 3003:3003/udp

volumes:
  postgres:
