name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: symfonia
          POSTGRES_DB: symfonia
          POSTGRES_USER: symfonia
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          prefix-key: "linux"
      - name: Build and Test with Nextest
        env:
          DATABASE_HOST: postgres
          DATABASE_USERNAME: symfonia
          DATABASE_PASSWORD: symfonia
          DATABASE_NAME: symfonia
          DATABASE_PORT: 5432
          SQLX_OFFLINE: true
          # This is only important for tests
          DATABASE_URL: postgres://symfonia:symfonia@postgres/symfonia
        run: |
          curl -L --proto '=https' --tlsv1.3 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cargo-nextest --secure --no-confirm --force
          cargo nextest run --all --verbose
