name: Docker compose smoketest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  deploy_compose:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          prefix-key: "linux"
      - name: Container build acceleration using rust-cache
        run: |
          SQLX_OFFLINE=true cargo build --release
      - name: Create .env file
        run: cp compose-example.env .env
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "compose.yaml"
          up-flags: "--build"
          down-flags: "-v"
